name: Bug report
description: Report a problem.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to report a bug or problem with the Paddle MCP server.

        Remember to remove sensitive information from screenshots, videos, or code samples before submitting.

        **Do not create issues for potential security vulnerabilities.** Please see the [Paddle Vulnerability Disclosure Policy](https://www.paddle.com/vulnerability-disclosure-policy) and report any vulnerabilities [using our form](https://vdp.paddle.com/p/Report-a-Vulnerability).

        Thanks for helping to make the Paddle platform better for everyone!
  - type: textarea
	    id: description
	    attributes:
	      label: What happened?
	      description: Describe the bug in a sentence or two. Feel free to add screenshots or a video to better explain!
	    validations:
	      required: true
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue type
      description: What type of issue are you experiencing?
      options:
        - Misunderstood request
        - Incorrect response
        - Product knowledge gap
        - API integration problem
        - Performance or latency problem
        - Other
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Explain how to reproduce this issue. We prefer a step-by-step walkthrough, where possible.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: conversation
    attributes:
      label: Conversation with AI agent
      description: Please share the relevant parts of your conversation with the AI agent. This helps us understand the context of the issue.
    validations:
      required: false
  - type: textarea
    id: prompts
    attributes:
      label: Prompts used
      description: If applicable, share the specific prompts you used that led to the issue.
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      description: Tell us what should happen when you encounter this bug.
    validations:
      required: true
  - type: textarea
    id: expected-ai-response
    attributes:
      label: What response did you expect from the MCP?
      description: Describe what you expected the MCP to understand or respond with.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Copy and paste any relevant logs. This is automatically formatted into code, so no need for backticks.
      render: shell
  - type: input
    id: conversation-link
    attributes:
      label: Conversation link
      description: If available, provide a link to the conversation where the issue occurred. Don't share conversations with sensitive information.
      placeholder: https://example.com/conversation/123
    validations:
      required: false
